# Generated by Django 2.2.2 on 2019-06-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=1000)),
                ('dob', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('offence', models.CharField(max_length=255)),
                ('caution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=50)),
                ('build', models.CharField(max_length=20)),
                ('hair', models.CharField(max_length=20)),
                ('eyes', models.CharField(max_length=20)),
                ('teeth', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=3)),
                ('complexion', models.CharField(max_length=20)),
                ('facial_hair', models.CharField(max_length=20)),
                ('tattoo', models.CharField(max_length=20)),
                ('scars', models.CharField(max_length=20)),
                ('face_shape', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Person')),
            ],
        ),
    ]
