# Generated by Django 2.2.2 on 2019-06-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0004_auto_20190618_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offences',
            new_name='Offence',
        ),
    ]
