# Generated by Django 2.2.2 on 2019-06-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0005_auto_20190618_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='permit',
            field=models.CharField(default=569854, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit', models.CharField(max_length=10)),
                ('offender', models.CharField(max_length=255)),
                ('vehicle', models.CharField(max_length=7)),
                ('fixed_penalty', models.CharField(max_length=10)),
                ('offence', models.CharField(max_length=255)),
                ('date_time_of_offence', models.CharField(max_length=10)),
                ('time_of_offence', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('enactment', models.CharField(max_length=1000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Person')),
            ],
        ),
    ]
