# Generated by Django 2.2.2 on 2019-06-28 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0006_auto_20190623_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='person',
        ),
        migrations.AddField(
            model_name='ticket',
            name='firstName',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='lastName',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
