# Generated by Django 2.2.2 on 2019-07-16 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0009_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='offence',
        ),
        migrations.AddField(
            model_name='offence',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='criminals.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='charge',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
