# Generated by Django 2.2.2 on 2019-07-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0010_auto_20190716_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offence',
        ),
    ]
