# Generated by Django 2.2.2 on 2019-07-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0012_offence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='charge',
        ),
    ]
