# Generated by Django 2.2.2 on 2019-07-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0013_remove_person_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offence',
            name='person',
        ),
    ]
