# Generated by Django 2.2.2 on 2019-07-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0014_remove_offence_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offence',
        ),
    ]
