# Generated by Django 2.2.2 on 2019-07-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0015_delete_offence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence', models.CharField(max_length=255)),
                ('enactment', models.CharField(max_length=1000)),
                ('fixed_penalty', models.CharField(max_length=10)),
                ('penalty_points', models.CharField(max_length=5)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('permit', models.CharField(max_length=10)),
                ('vehicle', models.CharField(max_length=7)),
                ('date_time_of_offence', models.CharField(max_length=10)),
                ('time_of_offence', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Offence')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Offence')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Person')),
            ],
        ),
    ]
