# Generated by Django 2.2.2 on 2019-07-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0016_charge_offence_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offence',
            name='enactment',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='fixed_penalty',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='penalty_points',
        ),
    ]
