# Generated by Django 2.2.2 on 2019-07-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0017_auto_20190716_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
