# Generated by Django 2.2.2 on 2019-07-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0020_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
