# Generated by Django 2.2.2 on 2019-08-06 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0021_auto_20190716_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.CharField(max_length=7)),
                ('car_make', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('car_year', models.CharField(max_length=4)),
                ('license_plate', models.CharField(max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_date', models.DateTimeField(auto_now=True)),
                ('date_time_of_offence', models.CharField(max_length=10)),
                ('time_of_offence', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Offence')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.Vehicle')),
            ],
        ),
    ]
