# Generated by Django 2.2.2 on 2019-08-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0022_ticket_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.CharField(default='https://i1.wp.com/smk.org.uk/wp-content/uploads/avatar.jpg?ssl=1', max_length=1000),
        ),
    ]
