# Generated by Django 2.2.2 on 2019-08-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0023_auto_20190806_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='alias',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.CharField(default='dd/mm/yyyy', max_length=12),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.CharField(default='N/A', max_length=2000),
        ),
    ]
