# Generated by Django 2.2.2 on 2019-08-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0027_auto_20190821_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='status',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
