# Generated by Django 2.2.2 on 2019-08-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0029_report_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
    ]
