# Generated by Django 2.2.2 on 2019-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0031_auto_20190821_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='build',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='complexion',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='eyes',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='face_shape',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='facial_hair',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='hair',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='height',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='desc',
            name='scars',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='tattoo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='teeth',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='desc',
            name='weight',
            field=models.CharField(default='', max_length=3),
        ),
    ]
